- import_tasks: debug.yml
  when: debug | default(false)
  tags: debug

- import_tasks: validate.yml
  tags: validation

- import_tasks: install.yml
  become: true
  tags: installation

- import_tasks: remove.yml
  tags: remove
