- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validate.yml
  tags: validation

- include: install.yml
  become: true
  tags: installation

- include: remove.yml
  tags: remove
